services:
   server:
      image: milaro/django-server:latest
      depends_on:
         - database
      env_file:
         - .env
      volumes:
         - .:/app
      command:
         - sh -c "python manage.py collectstatic --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
   nginx:
      image: milaro/nginx-server:latest
      ports:
         - 80:80
      volumes:
         - ./nginx/conf.d:/etc/nginx/conf.d
         - ./staticfiles:/static
      depends_on:
         - server
   database:
      image: postgres
      ports:
         - 5432:5432
      environment:
         - POSTGRES_PASSWORD=password
         - POSTGRES_USER=username
         - POSTGRES_DB=mydb
      restart: always
      volumes:
         - postgres_data:/var/lib/postgresql/data
volumes:
   postgres_data:
