# Generated by Django 4.2.2 on 2023-12-16 03:13

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(upload_to=apps.user.models.upload_to),
        ),
    ]
