# Generated by Django 4.2.2 on 2023-12-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_thumbnail_url_alter_user_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
    ]
